Moja_lista=[1, 17, 3, 5, 3, 4, 86, 90, 2, 21]
print(Moja_lista[0])
print(Moja_lista[-1])
print(len(Moja_lista))
print(min(Moja_lista))
print(max(Moja_lista))
print(sum(Moja_lista))
print(Moja_lista)
Moja_lista = sorted(Moja_lista)
print(Moja_lista)
Moja_lista.append(6)
print(Moja_lista)
Moja_lista.insert(4,12)
print(Moja_lista)
print(Moja_lista.pop())
print(Moja_lista)
Moja_lista.reverse()
print(Moja_lista)
Lista2 = [222]
print(Moja_lista+Lista2)
print(Moja_lista*5)
print(Moja_lista[:3])
print(Moja_lista[3:])
print(Moja_lista[1:8:2])
print(Moja_lista[::-1])

